# -*- coding: utf-8 -*-
"""Derives cv.bib and teaching.tex from the website's own sources.

papers.bib stays the single source of truth. This script only transforms:
  venue -> booktitle        (display string wins; biber's \DeclareSourcemap
                             would do this natively but biber is unavailable)
  literal en dash -> --     (T1/lmodern drops the raw UTF-8 codepoint)
  keywords = {group}        (drives \printbibliography filtering)
  addendum = {links+status} (custom fields are invisible to the bibtex backend,
                             so they are packed into a standard field)
"""
import re, os, sys

ROOT = '/apollo/users/dya/duo0301.github.io'
OUT  = os.path.dirname(os.path.abspath(__file__))

GROUP = {
    'Yang_2026': 'conference', 'Fleiner_2025': 'conference', 'Dasoulas_2024': 'conference',
    'Iferroudjene_2026': 'workshop', 'Yang_2025': 'workshop',
    'Dasoulas_2023': 'workshop', 'Yang_2023': 'workshop',
    'Dasoulas_2025': 'demo',
    'Dasoulas_2026': 'conference',
}
TIER   = {'Yang_2026': 'CORE A*'}
TRACK  = {'Yang_2026': 'Research track', 'Fleiner_2025': 'Resource track',
          'Dasoulas_2023': 'Accuracy track, 1st Prize'}
STATUS = {'Yang_2026': 'To appear', 'Iferroudjene_2026': 'To appear',
          'Dasoulas_2026': 'Accepted, in press'}

def tex_escape_url(u):
    return u.replace('%', '\\%').replace('#', '\\#').replace('&', '\\&')

def asset(u):
    return u if u.startswith('http') else 'https://duo0301.github.io/assets/pdf/' + u

def parse(path):
    s = open(path, encoding='utf-8').read()
    out = []
    for m in re.finditer(r'^@(\w+)\{([^,]+),(.*?)\n\}', s, re.S | re.M):
        d = dict((k.lower(), v.strip()) for k, v in
                 re.findall(r'^\s+(\w+)\s*=\s*\{(.*?)\},?$', m.group(3), re.M))
        out.append((m.group(1), m.group(2), d))
    return out

entries = parse(os.path.join(ROOT, '_bibliography/papers.bib'))
assert sorted(k for _, k, _ in entries) == sorted(GROUP), \
    'GROUP map out of sync with papers.bib: %s' % (set(GROUP) ^ {k for _, k, _ in entries})

DROP = {'abbr','bibtex_show','selected','topic','venue','author_note',
        'pdf','slides','poster','website','supp','url'}
KEEP_ORDER = ['title','author','booktitle','journal','publisher','series',
              'volume','pages','year','month','doi','issn','isbn',
              'keywords','addendum','note']

lines = ['% Generated by prepare.py from _bibliography/papers.bib -- do not edit.\n']
for etype, key, d in entries:
    d = dict(d)
    entry_author_raw = d.get('author', '')
    if d.get('venue'):
        if 'booktitle' in d: d['booktitle'] = d['venue']
        elif 'journal' in d: d['journal'] = d['venue']
    # daggers break bibtex name parsing and the bold-my-name test:
    # strip them from names and say who contributed equally, in words
    ann = []
    if d.get('author_note'):
        who = [a.replace('\u2020','').split(',')[0].strip()
               for a in entry_author_raw.split(' and ') if '\u2020' in a]
        ann.append('\\textdagger{} %s contributed equally'
                   % (' and '.join(who) if who else 'Equal contribution'))
    if d.get('author'):
        a = d['author'].replace('\u2020', '')
        # brace-protect and bold my own family name: biblatex's
        # \mkbibnamefamily hook does not fire reliably with the bibtex backend
        d['author'] = a
    if TRACK.get(key):  ann.append(TRACK[key])
    if TIER.get(key):   ann.append('\\textbf{%s}' % TIER[key].replace('*', '*'))
    if STATUS.get(key): ann.append('\\emph{%s}' % STATUS[key])
    links = []
    for label, field in ((r'\faFilePdf', 'pdf'), (r'\faFilePowerpoint', 'slides'),
                         (r'\faImage', 'poster'), (r'\faGlobe', 'website'),
                         (r'\faDatabase', 'supp')):
        if d.get(field):
            links.append('\\href{%s}{%s}' % (tex_escape_url(asset(d[field])), label))
    add = []
    if ann:   add.append('\\cvann{%s}' % ' \\cvdot{} '.join(ann))
    if links: add.append('\\cvlinks{%s}' % ' \\cvdot{} '.join(links))
    if add:   d['addendum'] = '\\\\' + ' \\cvdot{} '.join(add)
    d['keywords'] = GROUP[key]
    body = []
    for f in KEEP_ORDER:
        if d.get(f) and f not in DROP:
            body.append('  %-10s = {%s},' % (f, d[f]))
    lines.append('@%s{%s,\n%s\n}\n' % (etype, key, '\n'.join(body).rstrip(',')))

bib = '\n'.join(lines).replace('–', '--').replace('—', '---')
open(os.path.join(OUT, 'cv.bib'), 'w', encoding='utf-8').write(bib)

# ---- teaching + supervision, parsed from the site page
s = open(os.path.join(ROOT, '_pages/teaching.md'), encoding='utf-8').read()
s = re.sub(r'^---.*?^---', '', s, flags=re.S | re.M)
courses, theses, cur = [], [], None
for line in s.splitlines():
    if line.startswith('### '):
        cur = 'c' if 'course' in line.lower() else 't'; continue
    m = re.match(r'^- (.+)$', line.strip())
    if not m or cur is None: continue
    txt = m.group(1)
    lk = re.match(r'^\[(.*?)\]\((.*?)\)\s*(.*)$', txt)
    name, url = (lk.group(1), lk.group(2)) if lk else (txt, None)
    rest = lk.group(3) if lk else txt
    yr = re.search(r'academic year ([\d\-,\s]+)', rest)
    years = yr.group(1).strip().rstrip(')') if yr else ''
    years = re.sub(r'(\d{4})-(\d{2})(\d{2})', lambda m: m.group(1)+'--'+m.group(3), years)
    if not lk:
        name = re.sub(r'\s*\(academic year.*?\)\s*$', '', txt)
    name = name.replace('&', '\\&')
    (courses if cur == 'c' else theses).append((name, url, years))

def entry(name, url, years):
    label = '\\href{%s}{%s}' % (tex_escape_url(url), name) if url else name
    return '\\cvrow{%s}{%s}' % (years, label)

with open(os.path.join(OUT, 'teaching.tex'), 'w', encoding='utf-8') as f:
    f.write('%% Generated by prepare.py from _pages/teaching.md -- do not edit.\n')
    f.write('\\newcommand{\\CourseRows}{%\n' +
            '\n'.join(entry(*c) for c in courses) + '}\n')
    f.write('\\newcommand{\\ThesisRows}{%\n' +
            '\n'.join(entry(*t) for t in theses) + '}\n')

print('  cv.bib: %d entries  |  teaching.tex: %d courses, %d theses'
      % (len(entries), len(courses), len(theses)))
